'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.239
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CWcheat_Database_Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property abc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_PSX_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_PSX_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alwaystop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alwaystop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  PSPFTPDサーバーが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ftpf() As String
            Get
                Return ResourceManager.GetString("ftpf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  PSPFTPDサーバーが見つかりました
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ftps() As String
            Get
                Return ResourceManager.GetString("ftps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  開始アドレスが終了アドレスを超えてます に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ip1() As String
            Get
                Return ResourceManager.GetString("ip1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  有効なローカルアドレスを入力してください
        '''クラスA:10.0.0.0-10.255.255.255
        '''クラスB:172.16.0.0-172.31.255.255
        '''クラスC:192.168.0.0-192.168.255.255 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ip2() As String
            Get
                Return ResourceManager.GetString("ip2", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property new_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property psp_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("psp_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remove_PSX_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_PSX_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_PSX_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_PSX_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sony_playstation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sony_playstation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sony_playstation1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sony_playstation1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sony_psp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sony_psp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
